# Generated by Django 5.0.4 on 2024-04-12 06:23

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(upload_to=store.models.upload_image),
        ),
    ]
