# Generated by Django 5.0.4 on 2024-04-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='productimage',
        ),
    ]
