# Generated by Django 5.0.4 on 2024-04-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order_notes',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
