# Generated by Django 5.0.4 on 2024-04-17 07:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_ordercomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercomplete',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
